import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { NextFont } from "next/dist/compiled/@next/font";

const intelMonoFont : NextFont = localFont({
  src: "./fonts/Intel_One_Mono/IntelOneMono-VariableFont_wght.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className={`min-h-full flex flex-col ${intelMonoFont.className}`}>{children}</body>
    </html>
  );
}
